services:
  backend:
    build: ./backend
    container_name: elastic-nest-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
